version: "3.9"

services:
  backend:
    container_name: kanban-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/kanban-board
      N8N_WEBHOOK_URL: http://n8n:5678/webhook/kanban-export
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - mongo
      - n8n
    command: npm run start:prod

  mongo:
    image: mongo:6
    container_name: kanban-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  n8n:
    image: n8nio/n8n:1.106.3
    container_name: kanban-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  mongo_data:
  n8n_data:
